# Generated by Django 5.2.7 on 2025-10-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='is_approved',
        ),
    ]
