# Generated by Django 5.2.7 on 2025-10-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_remove_turf_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
