# Generated by Django 5.2.7 on 2025-10-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_alter_turf_latitude_alter_turf_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
