# Generated by Django 5.2.7 on 2025-10-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_alter_turf_latitude_alter_turf_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
