# Generated by Django 5.2.7 on 2025-11-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0009_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
