# Generated by Django 5.2.7 on 2025-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0010_booking_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirm_after_payment', 'Confirm After Payment'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
