# Generated by Django 5.2.7 on 2025-11-04 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0011_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamshuffler',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamshuffler',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teamshuffler',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_shufflers', to='turf.booking'),
        ),
    ]
